# Generated by Django 3.2.8 on 2021-10-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergySymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ColdSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name= 'MuscleSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FlatulenceSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DiarrheaSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ConstipationSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AllergiccontactSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UrticariaSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AllergicweatherSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ColdallergySymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ParasiteSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CoughSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
